# Generated by Django 4.2.30 on 2026-06-04 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_dispatch_map_layers'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patrolasset',
            new_name='incidents_p_active_75d495_idx',
            old_name='incidents_p_active_a82f80_idx',
        ),
        migrations.RenameIndex(
            model_name='patrolasset',
            new_name='incidents_p_latitud_fd6420_idx',
            old_name='incidents_p_latitud_e24ea0_idx',
        ),
    ]
