# Generated by Codex on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0004_rename_incidents_p_active_a82f80_idx_incidents_p_active_75d495_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="device_id",
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name="incident",
            name="pressed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="source",
            field=models.CharField(
                choices=[
                    ("CITIZEN_APP", "Citizen app"),
                    ("IOT_BUTTON", "IoT panic button"),
                ],
                db_index=True,
                default="CITIZEN_APP",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["source", "pressed_at"],
                name="inc_i_source_pressed_idx",
            ),
        ),
    ]
